from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(450, 540)
        font = QtGui.QFont()
        font.setPointSize(20)
        MainWindow.setFont(font)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Calculator = QtWidgets.QWidget(MainWindow)
        self.Calculator.setObjectName("Calculator")
        self.btnZero = QtWidgets.QPushButton(self.Calculator)
        self.btnZero.setGeometry(QtCore.QRect(20, 420, 70, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnZero.sizePolicy().hasHeightForWidth())
        self.btnZero.setSizePolicy(sizePolicy)
        self.btnZero.setBaseSize(QtCore.QSize(10, 10))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(25)
        self.btnZero.setFont(font)
        self.btnZero.setIconSize(QtCore.QSize(50, 20))
        self.btnZero.setObjectName("btnZero")
        self.btnDoubleZero = QtWidgets.QPushButton(self.Calculator)
        self.btnDoubleZero.setGeometry(QtCore.QRect(110, 420, 70, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDoubleZero.sizePolicy().hasHeightForWidth())
        self.btnDoubleZero.setSizePolicy(sizePolicy)
        self.btnDoubleZero.setBaseSize(QtCore.QSize(10, 10))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(25)
        self.btnDoubleZero.setFont(font)
        self.btnDoubleZero.setIconSize(QtCore.QSize(50, 20))
        self.btnDoubleZero.setObjectName("btnDoubleZero")
        self.btnDot = QtWidgets.QPushButton(self.Calculator)
        self.btnDot.setGeometry(QtCore.QRect(200, 420, 70, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDot.sizePolicy().hasHeightForWidth())
        self.btnDot.setSizePolicy(sizePolicy)
        self.btnDot.setBaseSize(QtCore.QSize(10, 10))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(40)
        self.btnDot.setFont(font)
        self.btnDot.setIconSize(QtCore.QSize(50, 20))
        self.btnDot.setObjectName("btnDot")
        self.btnEqual = QtWidgets.QPushButton(self.Calculator)
        self.btnEqual.setGeometry(QtCore.QRect(290, 420, 140, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnEqual.sizePolicy().hasHeightForWidth())
        self.btnEqual.setSizePolicy(sizePolicy)
        self.btnEqual.setBaseSize(QtCore.QSize(10, 10))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(40)
        self.btnEqual.setFont(font)
        self.btnEqual.setIconSize(QtCore.QSize(50, 20))
        self.btnEqual.setObjectName("btnEqual")
        self.btnOne = QtWidgets.QPushButton(self.Calculator)
        self.btnOne.setGeometry(QtCore.QRect(20, 330, 70, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnOne.sizePolicy().hasHeightForWidth())
        self.btnOne.setSizePolicy(sizePolicy)
        self.btnOne.setBaseSize(QtCore.QSize(10, 10))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(25)
        self.btnOne.setFont(font)
        self.btnOne.setIconSize(QtCore.QSize(50, 20))
        self.btnOne.setObjectName("btnOne")
        self.btnTwo = QtWidgets.QPushButton(self.Calculator)
        self.btnTwo.setGeometry(QtCore.QRect(110, 330, 70, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnTwo.sizePolicy().hasHeightForWidth())
        self.btnTwo.setSizePolicy(sizePolicy)
        self.btnTwo.setBaseSize(QtCore.QSize(10, 10))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(25)
        self.btnTwo.setFont(font)
        self.btnTwo.setIconSize(QtCore.QSize(50, 20))
        self.btnTwo.setObjectName("btnTwo")
        self.btnThree = QtWidgets.QPushButton(self.Calculator)
        self.btnThree.setGeometry(QtCore.QRect(200, 330, 70, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnThree.sizePolicy().hasHeightForWidth())
        self.btnThree.setSizePolicy(sizePolicy)
        self.btnThree.setBaseSize(QtCore.QSize(10, 10))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(25)
        self.btnThree.setFont(font)
        self.btnThree.setIconSize(QtCore.QSize(50, 20))
        self.btnThree.setObjectName("btnThree")
        self.btnFour = QtWidgets.QPushButton(self.Calculator)
        self.btnFour.setGeometry(QtCore.QRect(20, 240, 70, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnFour.sizePolicy().hasHeightForWidth())
        self.btnFour.setSizePolicy(sizePolicy)
        self.btnFour.setBaseSize(QtCore.QSize(10, 10))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(25)
        self.btnFour.setFont(font)
        self.btnFour.setIconSize(QtCore.QSize(50, 20))
        self.btnFour.setObjectName("btnFour")
        self.btnFive = QtWidgets.QPushButton(self.Calculator)
        self.btnFive.setGeometry(QtCore.QRect(110, 240, 70, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnFive.sizePolicy().hasHeightForWidth())
        self.btnFive.setSizePolicy(sizePolicy)
        self.btnFive.setBaseSize(QtCore.QSize(10, 10))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(25)
        self.btnFive.setFont(font)
        self.btnFive.setIconSize(QtCore.QSize(50, 20))
        self.btnFive.setObjectName("btnFive")
        self.btnSix = QtWidgets.QPushButton(self.Calculator)
        self.btnSix.setGeometry(QtCore.QRect(200, 240, 70, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSix.sizePolicy().hasHeightForWidth())
        self.btnSix.setSizePolicy(sizePolicy)
        self.btnSix.setBaseSize(QtCore.QSize(10, 10))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(25)
        self.btnSix.setFont(font)
        self.btnSix.setIconSize(QtCore.QSize(50, 20))
        self.btnSix.setObjectName("btnSix")
        self.btnSeven = QtWidgets.QPushButton(self.Calculator)
        self.btnSeven.setGeometry(QtCore.QRect(20, 150, 70, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSeven.sizePolicy().hasHeightForWidth())
        self.btnSeven.setSizePolicy(sizePolicy)
        self.btnSeven.setBaseSize(QtCore.QSize(10, 10))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(25)
        self.btnSeven.setFont(font)
        self.btnSeven.setIconSize(QtCore.QSize(50, 20))
        self.btnSeven.setObjectName("btnSeven")
        self.btnEight = QtWidgets.QPushButton(self.Calculator)
        self.btnEight.setGeometry(QtCore.QRect(110, 150, 70, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnEight.sizePolicy().hasHeightForWidth())
        self.btnEight.setSizePolicy(sizePolicy)
        self.btnEight.setBaseSize(QtCore.QSize(10, 10))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(25)
        self.btnEight.setFont(font)
        self.btnEight.setIconSize(QtCore.QSize(50, 20))
        self.btnEight.setObjectName("btnEight")
        self.btnNine = QtWidgets.QPushButton(self.Calculator)
        self.btnNine.setGeometry(QtCore.QRect(200, 150, 70, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnNine.sizePolicy().hasHeightForWidth())
        self.btnNine.setSizePolicy(sizePolicy)
        self.btnNine.setBaseSize(QtCore.QSize(10, 10))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(25)
        self.btnNine.setFont(font)
        self.btnNine.setIconSize(QtCore.QSize(50, 20))
        self.btnNine.setObjectName("btnNine")
        self.btnAddition = QtWidgets.QPushButton(self.Calculator)
        self.btnAddition.setGeometry(QtCore.QRect(290, 330, 60, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAddition.sizePolicy().hasHeightForWidth())
        self.btnAddition.setSizePolicy(sizePolicy)
        self.btnAddition.setBaseSize(QtCore.QSize(10, 10))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(50)
        self.btnAddition.setFont(font)
        self.btnAddition.setIconSize(QtCore.QSize(50, 20))
        self.btnAddition.setObjectName("btnAddition")
        self.btnSubtraction = QtWidgets.QPushButton(self.Calculator)
        self.btnSubtraction.setGeometry(QtCore.QRect(369, 330, 61, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSubtraction.sizePolicy().hasHeightForWidth())
        self.btnSubtraction.setSizePolicy(sizePolicy)
        self.btnSubtraction.setBaseSize(QtCore.QSize(10, 10))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(50)
        self.btnSubtraction.setFont(font)
        self.btnSubtraction.setIconSize(QtCore.QSize(50, 20))
        self.btnSubtraction.setObjectName("btnSubtraction")
        self.btnMultiplication = QtWidgets.QPushButton(self.Calculator)
        self.btnMultiplication.setGeometry(QtCore.QRect(290, 240, 60, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMultiplication.sizePolicy().hasHeightForWidth())
        self.btnMultiplication.setSizePolicy(sizePolicy)
        self.btnMultiplication.setBaseSize(QtCore.QSize(10, 10))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(50)
        self.btnMultiplication.setFont(font)
        self.btnMultiplication.setIconSize(QtCore.QSize(50, 20))
        self.btnMultiplication.setObjectName("btnMultiplication")
        self.btnDivision = QtWidgets.QPushButton(self.Calculator)
        self.btnDivision.setGeometry(QtCore.QRect(369, 240, 61, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDivision.sizePolicy().hasHeightForWidth())
        self.btnDivision.setSizePolicy(sizePolicy)
        self.btnDivision.setBaseSize(QtCore.QSize(10, 10))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(50)
        self.btnDivision.setFont(font)
        self.btnDivision.setIconSize(QtCore.QSize(50, 20))
        self.btnDivision.setObjectName("btnDivision")
        self.btnModulus = QtWidgets.QPushButton(self.Calculator)
        self.btnModulus.setGeometry(QtCore.QRect(290, 150, 60, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnModulus.sizePolicy().hasHeightForWidth())
        self.btnModulus.setSizePolicy(sizePolicy)
        self.btnModulus.setBaseSize(QtCore.QSize(10, 10))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(35)
        self.btnModulus.setFont(font)
        self.btnModulus.setIconSize(QtCore.QSize(50, 20))
        self.btnModulus.setObjectName("btnModulus")
        self.btnClear = QtWidgets.QPushButton(self.Calculator)
        self.btnClear.setGeometry(QtCore.QRect(370, 150, 60, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnClear.sizePolicy().hasHeightForWidth())
        self.btnClear.setSizePolicy(sizePolicy)
        self.btnClear.setBaseSize(QtCore.QSize(10, 10))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(23)
        self.btnClear.setFont(font)
        self.btnClear.setIconSize(QtCore.QSize(50, 20))
        self.btnClear.setObjectName("btnClear")
        self.txtDisplay = QtWidgets.QTextEdit(self.Calculator)
        self.txtDisplay.setGeometry(QtCore.QRect(10, 10, 430, 120))
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.txtDisplay.setFont(font)
        self.txtDisplay.setStyleSheet("")
        self.txtDisplay.setObjectName("txtDisplay")
        MainWindow.setCentralWidget(self.Calculator)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("Simple Calculator", "Simple Calculator"))
        self.btnZero.setText(_translate("MainWindow", "0"))
        self.btnDoubleZero.setText(_translate("MainWindow", "00"))
        self.btnDot.setText(_translate("MainWindow", "."))
        self.btnEqual.setText(_translate("MainWindow", "="))
        self.btnOne.setText(_translate("MainWindow", "1"))
        self.btnTwo.setText(_translate("MainWindow", "2"))
        self.btnThree.setText(_translate("MainWindow", "3"))
        self.btnFour.setText(_translate("MainWindow", "4"))
        self.btnFive.setText(_translate("MainWindow", "5"))
        self.btnSix.setText(_translate("MainWindow", "6"))
        self.btnSeven.setText(_translate("MainWindow", "7"))
        self.btnEight.setText(_translate("MainWindow", "8"))
        self.btnNine.setText(_translate("MainWindow", "9"))
        self.btnAddition.setText(_translate("MainWindow", "+"))
        self.btnSubtraction.setText(_translate("MainWindow", "-"))
        self.btnMultiplication.setText(_translate("MainWindow", "*"))
        self.btnDivision.setText(_translate("MainWindow", "/"))
        self.btnModulus.setText(_translate("MainWindow", "%"))
        self.btnClear.setText(_translate("MainWindow", "AC"))